[package]
name = "unirun-interface"
version = "0.5.0-alpha"
edition = "2021"

[dependencies]
glib = { workspace = true }
gio = { workspace = true }
uuid_crate = { version = "1.10", features = ["v4", "serde"], package = "uuid" }
serde = { workspace = true }
serde_json = { workspace = true }
