[package]
name = "unirun-interface"
version = "0.3.0-alpha"
edition = "2021"

[dependencies]
glib = { workspace = true }
gio = { workspace = true }
uuid = { version = "1.10", features = ["v4", "serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
